element_list:
  path :    /list
  defaults: { _controller: PdfGenesisElementBundle:Element:list }

element_ajax_position_change:
  path :    /ajax-position-change
  defaults: { _controller: PdfGenesisElementBundle:Element:ajaxPositionChange }
  options:
      expose: true


element_ajax_size_change:
  path :    /ajax-size-change
  defaults: { _controller: PdfGenesisElementBundle:Element:ajaxSizeChange }
  options:
      expose: true