#pdf_genesis_element_index:
#    path:     /
#    defaults: { _controller: PdfGenesisElementBundle:Default:index }





pdf_genesis_element_file:
    resource: "@PdfGenesisElementBundle/Resources/config/routing/file.yml"
    prefix:   /file


pdf_genesis_element_element:
    resource: "@PdfGenesisElementBundle/Resources/config/routing/element.yml"
    prefix:   /


