#pdf_genesis_element_index:
#    path:     /
#    defaults: { _controller: PdfGenesisElementBundle:Default:index }


import_file:
     path :    /import-file
     defaults: { _controller: PdfGenesisElementBundle:File:import }
