services:
     pdf_genesis.event_subscriber.element:
         class: PdfGenesis\ElementBundle\EventListener\ElementSubscriber
         arguments: ["@doctrine.orm.entity_manager"]
         calls:
               - [ setContainer,[ @service_container ] ]
         tags:
               - {name: kernel.event_subscriber }