<?php

namespace PdfGenesis\DocumentBundle\Repository\Document;

/**
 * DocumentPDFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentPDFRepository extends \Doctrine\ORM\EntityRepository
{
}
