homepage:
    path:     /
    defaults: { _controller: PdfGenesisCoreBundle:Default:index }

design:
    path:     /design
    defaults: { _controller: PdfGenesisCoreBundle:Default:design }

user:
    resource: "@PdfGenesisCoreBundle/Resources/config/routing/user.yml"
    prefix:   /user

