user_index:
    path:     /
    defaults: { _controller: PdfGenesisCoreBundle:User:index }

user_data:
    path:     /personal-data
    defaults: { _controller: PdfGenesisCoreBundle:User:getData }

user_library:
    path:     /get-library
    defaults: { _controller: PdfGenesisCoreBundle:User:getLibrary }


user_ajax_update:
    path:     /update-user-ajax
    defaults: { _controller: PdfGenesisCoreBundle:User:updateUserAjax }
    options:
               expose: true

import_user_picture:
     path :    /import-picture
     defaults: { _controller: PdfGenesisCoreBundle:User:importPicture }