user_index:
    path:     /
    defaults: { _controller: PdfGenesisCoreBundle:User:index }

user_data:
    path:     /personal-data
    defaults: { _controller: PdfGenesisCoreBundle:User:getData }

user_library:
    path:     /get-library
    defaults: { _controller: PdfGenesisCoreBundle:User:getLibrary }


user_ajax_update:
    path:     /update-user-ajax
    defaults: { _controller: PdfGenesisCoreBundle:User:udpateUserAjax }
    options:
               expose: true