services:
     pdf_genesis.event_subscriber.element:
         class: PdfGenesis\CoreBundle\EventListener\ElementSubscriber
         arguments: ["@doctrine.orm.entity_manager"]
         calls:
            - [ setContainer,[ @service_container ] ]
         tags:
            - {name: kernel.event_subscriber }

     pdf_genesis.event_listener.page:
         class: PdfGenesis\DocumentBundle\EventListener\PageListener
         arguments:  ["@doctrine.orm.entity_manager"]
         tags:
            - { name: kernel.event_listener, event: pdf_genesis.page.activate, method: activate }

     fos_user.listener.flash:
         class: PdfGenesis\CoreBundle\EventListener\FlashListener
         arguments:  ["@session", "@translator"]
         tags:
            - {name: kernel.event_subscriber }


#    pdf_genesis_core.example:
#        class: PdfGenesis\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]