services:
     pdf_genesis.event_listener.element:
         class: PdfGenesis\ElementBundle\EventListener\ElementListener
         arguments: ["@doctrine.orm.entity_manager"]
         tags:
            - { name: kernel.event_listener, event: pdf_genesis.element.create, method: create }


#    pdf_genesis_core.example:
#        class: PdfGenesis\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]