#pdf_genesis_document_index:
#    path:     /
#    defaults: { _controller: PdfGenesisDocumentBundle::index }

new_document:
     path:    /new-document
     defaults: { _controller: PdfGenesisDocumentBundle:Document:new }

generate_pdf:
     path:    /generate-pdf
     defaults: { _controller: PdfGenesisDocumentBundle:Pdf:generate }

generate_new_page:
     path:   /generate-page
     defaults: { _controller: PdfGenesisDocumentBundle:Document:newPage }

change_page:
     path:   /change-page
     defaults: { _controller: PdfGenesisDocumentBundle:Document:changePage }

document_update_title_description:
     path:    /update-title-description
     defaults: { _controller: PdfGenesisDocumentBundle:Document:updateTitleDescription }

#document_save:
#     path:    /save-document/{id}
#     defaults: { _controller: PdfGenesisDocumentBundle:Document:saveDocument }
#



document_save_ajax:
     path:    /save-document_ajax
     defaults: { _controller: PdfGenesisDocumentBundle:Document:saveDocumentAjax }
     options:
           expose: true

document_data_ajax:
     path:    /data-document_ajax
     defaults: { _controller: PdfGenesisDocumentBundle:Document:dataDocumentAjax }
     options:
           expose: true

document_update_ajax:
     path:    /update-document_ajax
     defaults: { _controller: PdfGenesisDocumentBundle:Document:updateDocumentAjax }
     options:
           expose: true



library_index:
     path:  /library/{id}
     defaults: { _controller: PdfGenesisDocumentBundle:Library:index }
