#pdf_genesis_document_index:
#    path:     /
#    defaults: { _controller: PdfGenesisDocumentBundle::index }

new_document:
     path:    /new-document
     defaults: { _controller: PdfGenesisDocumentBundle:Document:new }

generate_pdf:
     path:    /generate-pdf
     defaults: { _controller: PdfGenesisDocumentBundle:Pdf:generate }

generate_new_page:
     path:   /generate-page
     defaults: { _controller: PdfGenesisDocumentBundle:Document:newPage }

change_page:
     path:   /change-page
     defaults: { _controller: PdfGenesisDocumentBundle:Document:changePage }

document_update_title_description:
     path:    /update-title-description
     defaults: { _controller: PdfGenesisDocumentBundle:Document:updateTitleDescription }


library_index:
     path:  /library/{id}
     defaults: { _controller: PdfGenesisDocumentBundle:Library:index }