services:
#    pdf_genesis_document.example:
#        class: PdfGenesis\DocumentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     pdf_genesis_document.subscriber:
         class:  PdfGenesis\DocumentBundle\EventListener\DocumentSubscriber
         arguments:  ["@doctrine.orm.entity_manager", "@security.token_storage"]
         tags:
          - {name: kernel.event_subscriber }
